# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fields.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_field(object):
    def setupUi(self, field):
        field.setObjectName("field")
        field.resize(742, 526)
        self.buttonBox = QtWidgets.QDialogButtonBox(field)
        self.buttonBox.setGeometry(QtCore.QRect(560, 490, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget = QtWidgets.QWidget(field)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 581, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.description = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.description.setObjectName("description")
        self.gridLayout.addWidget(self.description, 2, 1, 1, 1)
        self.inverse = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.inverse.setObjectName("inverse")
        self.gridLayout.addWidget(self.inverse, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.ttype = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.ttype.setObjectName("ttype")
        self.ttype.addItem("")
        self.ttype.addItem("")
        self.ttype.addItem("")
        self.ttype.addItem("")
        self.ttype.addItem("")
        self.ttype.addItem("")
        self.ttype.addItem("")
        self.ttype.addItem("")
        self.ttype.addItem("")
        self.ttype.addItem("")
        self.ttype.addItem("")
        self.ttype.addItem("")
        self.ttype.addItem("")
        self.ttype.addItem("")
        self.gridLayout.addWidget(self.ttype, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 2, 1, 1)
        self.column2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.column2.setObjectName("column2")
        self.gridLayout.addWidget(self.column2, 3, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.default_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.default_2.setObjectName("default_2")
        self.gridLayout.addWidget(self.default_2, 4, 1, 1, 1)
        self.compute = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.compute.setObjectName("compute")
        self.gridLayout.addWidget(self.compute, 0, 3, 1, 1)
        self.column1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.column1.setObjectName("column1")
        self.gridLayout.addWidget(self.column1, 2, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.relation_table = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.relation_table.setObjectName("relation_table")
        self.gridLayout.addWidget(self.relation_table, 1, 3, 1, 1)
        self.comodel_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.comodel_name.setObjectName("comodel_name")
        self.gridLayout.addWidget(self.comodel_name, 4, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.domain = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.domain.setObjectName("domain")
        self.gridLayout.addWidget(self.domain, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 2, 1, 1)
        self.related = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.related.setObjectName("related")
        self.gridLayout.addWidget(self.related, 5, 3, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(field)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 360, 491, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.is_readonly = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.is_readonly.setObjectName("readonly")
        self.horizontalLayout.addWidget(self.is_readonly)
        self.is_required = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.is_required.setObjectName("required")
        self.horizontalLayout.addWidget(self.is_required)
        self.is_store = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.is_store.setObjectName("store")
        self.horizontalLayout.addWidget(self.is_store)
        self.is_copy = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.is_copy.setObjectName("copy")
        self.horizontalLayout.addWidget(self.is_copy)
        self.is_index = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.is_index.setObjectName("index")
        self.horizontalLayout.addWidget(self.is_index)
        self.label_5.setBuddy(self.relation_table)
        self.label_9.setBuddy(self.comodel_name)
        self.label_7.setBuddy(self.column2)
        self.label_11.setBuddy(self.inverse)
        self.label_4.setBuddy(self.compute)
        self.label_6.setBuddy(self.column1)
        self.label_8.setBuddy(self.default_2)
        self.label_10.setBuddy(self.domain)
        self.label_3.setBuddy(self.description)
        self.label.setBuddy(self.name)
        self.label_2.setBuddy(self.ttype)
        self.label_12.setBuddy(self.comodel_name)

        self.retranslateUi(field)
        self.buttonBox.accepted.connect(field.accept)
        self.buttonBox.rejected.connect(field.reject)
        QtCore.QMetaObject.connectSlotsByName(field)

    def retranslateUi(self, field):
        _translate = QtCore.QCoreApplication.translate
        field.setWindowTitle(_translate("field", "Dialog"))
        self.label_5.setText(_translate("field", "relation_table"))
        self.ttype.setItemText(0, _translate("field", "char"))
        self.ttype.setItemText(1, _translate("field", "binary"))
        self.ttype.setItemText(2, _translate("field", "text"))
        self.ttype.setItemText(3, _translate("field", "html"))
        self.ttype.setItemText(4, _translate("field", "integer"))
        self.ttype.setItemText(5, _translate("field", "float"))
        self.ttype.setItemText(6, _translate("field", "monetary"))
        self.ttype.setItemText(7, _translate("field", "boolean"))
        self.ttype.setItemText(8, _translate("field", "selection"))
        self.ttype.setItemText(9, _translate("field", "date"))
        self.ttype.setItemText(10, _translate("field", "datetime"))
        self.ttype.setItemText(11, _translate("field", "many2many"))
        self.ttype.setItemText(12, _translate("field", "one2many"))
        self.ttype.setItemText(13, _translate("field", "many2one"))
        self.label_9.setText(_translate("field", "comodel_name"))
        self.label_7.setText(_translate("field", "column2"))
        self.label_11.setText(_translate("field", "inverse"))
        self.label_4.setText(_translate("field", "compute"))
        self.label_6.setText(_translate("field", "column1"))
        self.label_8.setText(_translate("field", "default"))
        self.label_10.setText(_translate("field", "domain"))
        self.label_3.setText(_translate("field", "description"))
        self.label.setText(_translate("field", "name"))
        self.label_2.setText(_translate("field", "ttype"))
        self.label_12.setText(_translate("field", "related"))
        self.is_readonly.setText(_translate("field", "readonly"))
        self.is_required.setText(_translate("field", "required"))
        self.is_store.setText(_translate("field", "store"))
        self.is_copy.setText(_translate("field", "copy"))
        self.is_index.setText(_translate("field", "index"))

