# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_model(object):
    def setupUi(self, model):
        model.setObjectName("model")
        model.resize(1136, 711)
        self.centralwidget = QtWidgets.QWidget(model)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 571, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.order = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.order.setObjectName("order")
        self.gridLayout.addWidget(self.order, 4, 1, 1, 1)
        self.name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.inherit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.inherit.setEnabled(True)
        self.inherit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.inherit.setObjectName("inherit")
        self.gridLayout.addWidget(self.inherit, 3, 1, 1, 1)
        self.rec_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.rec_name.setEnabled(True)
        self.rec_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rec_name.setObjectName("rec_name")
        self.gridLayout.addWidget(self.rec_name, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.table_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.table_name.setEnabled(True)
        self.table_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.table_name.setObjectName("table_name")
        self.gridLayout.addWidget(self.table_name, 1, 1, 1, 1)
        self.description = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.description.setObjectName("description")
        self.gridLayout.addWidget(self.description, 5, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 390, 1111, 251))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(14)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(78)
        self.auto_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.auto_2.setGeometry(QtCore.QRect(630, 10, 71, 16))
        self.auto_2.setObjectName("auto_2")
        self.add_field = QtWidgets.QPushButton(self.centralwidget)
        self.add_field.setGeometry(QtCore.QRect(620, 330, 89, 23))
        self.add_field.setObjectName("add_field")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(990, 20, 81, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.save = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.save.setObjectName("save")
        self.verticalLayout.addWidget(self.save)
        self.generate = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.generate.setObjectName("generate")
        self.verticalLayout.addWidget(self.generate)
        model.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(model)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1136, 23))
        self.menubar.setObjectName("menubar")
        self.menuModule = QtWidgets.QMenu(self.menubar)
        self.menuModule.setObjectName("menuModule")
        self.menuModel = QtWidgets.QMenu(self.menubar)
        self.menuModel.setObjectName("menuModel")
        self.menuOpEN = QtWidgets.QMenu(self.menubar)
        self.menuOpEN.setObjectName("menuOpEN")
        self.menufield = QtWidgets.QMenu(self.menubar)
        self.menufield.setObjectName("menufield")
        model.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(model)
        self.statusbar.setObjectName("statusbar")
        model.setStatusBar(self.statusbar)
        self.actionConnection = QtWidgets.QAction(model)
        self.actionConnection.setObjectName("actionConnection")
        self.actionCreate = QtWidgets.QAction(model)
        self.actionCreate.setObjectName("actionCreate")
        self.actionSelect = QtWidgets.QAction(model)
        self.actionSelect.setObjectName("actionSelect")
        self.menuOpEN.addAction(self.actionConnection)
        self.menubar.addAction(self.menuOpEN.menuAction())
        self.menubar.addAction(self.menuModule.menuAction())
        self.menubar.addAction(self.menuModel.menuAction())
        self.menubar.addAction(self.menufield.menuAction())

        self.retranslateUi(model)
        QtCore.QMetaObject.connectSlotsByName(model)
        model.setTabOrder(self.name, self.table_name)
        model.setTabOrder(self.table_name, self.rec_name)
        model.setTabOrder(self.rec_name, self.inherit)
        model.setTabOrder(self.inherit, self.order)
        model.setTabOrder(self.order, self.tableWidget)

    def retranslateUi(self, model):
        _translate = QtCore.QCoreApplication.translate
        model.setWindowTitle(_translate("model", "MainWindow"))
        self.label_8.setText(_translate("model", "rec_name"))
        self.label_2.setText(_translate("model", "inherit"))
        self.label.setText(_translate("model", "name"))
        self.label_5.setText(_translate("model", "description"))
        self.label_7.setText(_translate("model", "table_name"))
        self.label_3.setText(_translate("model", "order"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("model", "name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("model", "model_name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("model", "string"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("model", "help"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("model", "comodel_name"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("model", "related"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("model", "groups"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("model", "inverse"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("model", "compute"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("model", "copy"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("model", "index"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("model", "readonly"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("model", "required"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("model", "store"))
        self.auto_2.setText(_translate("model", "auto"))
        self.add_field.setText(_translate("model", "add field"))
        self.save.setText(_translate("model", "save"))
        self.generate.setText(_translate("model", "generate"))
        self.menuModule.setTitle(_translate("model", "Module"))
        self.menuModel.setTitle(_translate("model", "Model"))
        self.menuOpEN.setTitle(_translate("model", "Edit"))
        self.menufield.setTitle(_translate("model", "Field"))
        self.actionConnection.setText(_translate("model", "Connection"))
        self.actionCreate.setText(_translate("model", "Create"))
        self.actionSelect.setText(_translate("model", "Select"))

